alter table SPEEDYPIZZAAPP_STAFF add constraint FK_SPEEDYPIZZAAPP_STAFF_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_SPEEDYPIZZAAPP_STAFF_ON_USER on SPEEDYPIZZAAPP_STAFF (USER_ID);
