alter table SPEEDYPIZZAAPP_ORDER_LINE add constraint FK_SPEEDYPIZZAAPP_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZAAPP_ORDER(ID);
alter table SPEEDYPIZZAAPP_ORDER_LINE add constraint FK_SPEEDYPIZZAAPP_ORDER_LINE_ON_DISH foreign key (DISH_ID) references SPEEDYPIZZAAPP_DISH(ID);
create index IDX_SPEEDYPIZZAAPP_ORDER_LINE_ON_ORDER on SPEEDYPIZZAAPP_ORDER_LINE (ORDER_ID);
create index IDX_SPEEDYPIZZAAPP_ORDER_LINE_ON_DISH on SPEEDYPIZZAAPP_ORDER_LINE (DISH_ID);
