alter table SPEEDYPIZZAAPP_DISH add constraint FK_SPEEDYPIZZAAPP_DISH_ON_DISH_TYPE foreign key (DISH_TYPE_ID) references SPEEDYPIZZAAPP_DISH_TYPE(ID);
create index IDX_SPEEDYPIZZAAPP_DISH_ON_DISH_TYPE on SPEEDYPIZZAAPP_DISH (DISH_TYPE_ID);
